name: C++ CI

on:
  push:
    branches: [ main,add_cicd_vcpkg ]
  pull_request:
    branches: [ main,add_cicd_vcpkg ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: cmake --build build --target test --config Release
